name: CMake_Ubuntu

on: 
  push:
    branches: 
      - master_cmake

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:      
    - uses: actions/checkout@v1
    - name: Print Machine Status
      run: |
            cat /proc/cpuinfo
    - name: Install generic prerequisites
      run: |
           sudo apt install -y libtbb-dev libavcodec-dev libavutil-dev libavformat-dev libswscale-dev libjpeg-dev libpng-dev libopenblas-dev liblapacke-dev
    - name: Install Qt
      run: |
            sudo apt install -y qt5-default qtscript-tools qtscript5-dev libqt5serialport5-dev
    - name: Install OpenCV prerequisites
      run: |
            sudo apt install -y libvtk6-dev
    - name: Install OpenCV
      run: |
            wget http://calvrack.ru:3080/exposed-drone/opencv/OpenCV-3.4.6-x86_64-libs.deb
            wget http://calvrack.ru:3080/exposed-drone/opencv/OpenCV-3.4.6-x86_64-dev.deb
            sudo dpkg -i OpenCV-3.4.6-x86_64-libs.deb OpenCV-3.4.6-x86_64-dev.deb            
    - name: Prepare build folder
      run: |
           ls
           pwd
           mkdir build
           cd build              
    - name: Cmake    
      run: |
           cd build
           cmake ..
    - name: Make 
      run: |
           cd build
           make -j 2 VERBOSE=1

