name: CMake_Ubuntu

on: 
  push:
    branches: 
      - master_cmake

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:      
    - uses: actions/checkout@v1
    - name: Print Machine Status
      run: |
            cat /proc/cpuinfo
    - name: Install generic prerequisites (Download opencv contrib)
      run: |
           wget https://github.com/opencv/opencv_contrib/archive/master.zip .
